added local vars and fixed code indentation

diff --git a/src/tomb b/src/tomb
--- a/src/tomb
+++ b/src/tomb
@@ -898,17 +898,17 @@ list_tombs() {
     local mounted_tombs tombname tombmount
     local tombfs tombfsopt tombtot
     local tombused tombavail tombpercent
-    local tombp tombsince 
+    local tombp tombsince t ts h
     local mapper mtomb mount_hooks 
 
-    if [ $1 ]; then
+    if [[ ! -z $1 ]]; then
 	    # list a specific tomb
 	    mounted_tombs=`mount -l |
-        awk -vtomb="[$1]" '/^\/dev\/mapper\/tomb/ { if($7==tomb) print $1 ";" $3 ";" $5 ";" $6 ";" $7 }'`
+            awk -vtomb="[$1]" '/^\/dev\/mapper\/tomb/ { if($7==tomb) print $1 ";" $3 ";" $5 ";" $6 ";" $7 }'`
     else
 	    # list all open tombs
 	    mounted_tombs=`mount -l |
-        awk '/^\/dev\/mapper\/tomb/ { print $1 ";" $3 ";" $5 ";" $6 ";" $7 }'`
+            awk '/^\/dev\/mapper\/tomb/ { print $1 ";" $3 ";" $5 ";" $6 ";" $7 }'`
     fi
     # 1 = full mapper path
     # 2 = mountpont
@@ -916,68 +916,68 @@ list_tombs() {
     # 4 = mount options
     # 5 = name
 
-    if ! [ $mounted_tombs ]; then
-	if [ $1 ]; then
-	    error "There seems to be no open tomb engraved as [${1}]"
-	else
-	    error "I can't see any open tomb, may they all rest in peace."
-	fi
-	exit 1
+    if  [[ -z $mounted_tombs ]]; then
+	    if [[ ! -z $1 ]]; then
+	        error "There seems to be no open tomb engraved as [${1}]"
+	    else
+	        error "I can't see any open tomb, may they all rest in peace."
+	    fi
+	    exit 1
     fi
 
     
     for t in ${(f)mounted_tombs}; do
-	mapper=`basename ${t[(ws:;:)1]}`
+	    mapper=`basename ${t[(ws:;:)1]}`
 
-	tombname=${t[(ws:;:)5]}
-	tombmount=${t[(ws:;:)2]}
-	tombfs=${t[(ws:;:)3]}
-	tombfsopts=${t[(ws:;:)4]}
+	    tombname=${t[(ws:;:)5]}
+	    tombmount=${t[(ws:;:)2]}
+	    tombfs=${t[(ws:;:)3]}
+	    tombfsopts=${t[(ws:;:)4]}
 
-	# calculate tomb size
-	ts=`df -hP /dev/mapper/$mapper |
-    awk "/mapper/"' { print $2 ";" $3 ";" $4 ";" $5 }'`
-	tombtot=${ts[(ws:;:)1]}
-	tombused=${ts[(ws:;:)2]}
-	tombavail=${ts[(ws:;:)3]}
-	tombpercent=${ts[(ws:;:)4]}
-    tombp=${tombpercent%%%}
-	tombsince=`date --date=@${mapper[(ws:.:)3]} +%c`
+	    # calculate tomb size
+	    ts=`df -hP /dev/mapper/$mapper |
+            awk "/mapper/"' { print $2 ";" $3 ";" $4 ";" $5 }'`
+	    tombtot=${ts[(ws:;:)1]}
+	    tombused=${ts[(ws:;:)2]}
+	    tombavail=${ts[(ws:;:)3]}
+	    tombpercent=${ts[(ws:;:)4]}
+        tombp=${tombpercent%%%}
+	    tombsince=`date --date=@${mapper[(ws:.:)3]} +%c`
 
-	# breaking up such strings is good for translation
-	print -n "$fg[green]$tombname"
-	print -n "$fg[white] open on "
-	print -n "$fg_bold[white]$tombmount"
-	print -n "$fg_no_bold[white] using "
-	print "$fg_bold[white]$tombfs $tombfsopts"
-
-	print -n "$fg_no_bold[green]$tombname"
-	print -n "$fg[white] size "
-	print -n "$fg_bold[white]$tombtot"
-	print -n "$fg_no_bold[white] of which "
-	print -n "$fg_bold[white]$tombused"
-	print -n "$fg_no_bold[white] used "
-	print -n "$fg_bold[white]$tombavail"
-	print -n "$fg_no_bold[white] free ("
-	print -n "$fg_bold[white]$tombpercent"
-	print "$fg_no_bold[white] full)"
-    if [[ ${tombp} -ge 90 ]]; then
-         error "your tomb is almost full!"
-    fi
-	print -n "$fg_no_bold[green]$tombname"
-	print -n "$fg_no_bold[white] open since "
-	print "$fg_bold[white]$tombsince$fg_no_bold[white]"
-	
-	# now check hooks
-	mtomb=`sed 's:\/:\\\/:g' <<< $tombmount`
-	mounted_hooks=`mount | awk "/^$mtomb/"' {print $1 ";" $3}'`
-	for h in ${(f)mounted_hooks}; do
+	    # breaking up such strings is good for translation
 	    print -n "$fg[green]$tombname"
-	    print -n "$fg_no_bold[white] hooks "
-	    print -n "$fg_bold[white]`basename ${h[(ws:;:)1]}`"
-	    print -n "$fg_no_bold[white] on "
-	    print "$fg_bold[white]${h[(ws:;:)2]}$fg_no_bold[white]"
-	done
+	    print -n "$fg[white] open on "
+	    print -n "$fg_bold[white]$tombmount"
+	    print -n "$fg_no_bold[white] using "
+	    print "$fg_bold[white]$tombfs $tombfsopts"
+
+	    print -n "$fg_no_bold[green]$tombname"
+	    print -n "$fg[white] size "
+	    print -n "$fg_bold[white]$tombtot"
+	    print -n "$fg_no_bold[white] of which "
+	    print -n "$fg_bold[white]$tombused"
+	    print -n "$fg_no_bold[white] used "
+	    print -n "$fg_bold[white]$tombavail"
+	    print -n "$fg_no_bold[white] free ("
+	    print -n "$fg_bold[white]$tombpercent"
+	    print "$fg_no_bold[white] full)"
+        if [[ ${tombp} -ge 90 ]]; then
+            error "your tomb is almost full!"
+        fi
+	    print -n "$fg_no_bold[green]$tombname"
+	    print -n "$fg_no_bold[white] open since "
+	    print "$fg_bold[white]$tombsince$fg_no_bold[white]"
+	
+	    # now check hooks
+	    mtomb=`sed 's:\/:\\\/:g' <<< $tombmount`
+	    mounted_hooks=`mount | awk "/^$mtomb/"' {print $1 ";" $3}'`
+	    for h in ${(f)mounted_hooks}; do
+	        print -n "$fg[green]$tombname"
+	        print -n "$fg_no_bold[white] hooks "
+	        print -n "$fg_bold[white]`basename ${h[(ws:;:)1]}`"
+	        print -n "$fg_no_bold[white] on "
+	        print "$fg_bold[white]${h[(ws:;:)2]}$fg_no_bold[white]"
+	    done
     done
 }
 
